server.port=${PORT:8083}
spring.application.name=ms-cita
jwt.secret=${JWT_SECRET:7Fq9Lm2Zx8RpQw4Tn6Vy1Ks5Db3Ha0CeSilvestre1313.}

#  Oracle Autonomous Database (Wallet) 
spring.datasource.url=jdbc:oracle:thin:@a1s2pvaey78cesbo_medium?TNS_ADMIN=${TNS_ADMIN:src/main/resources/wallet}
spring.datasource.username=${DB_USERNAME:ADMIN}
spring.datasource.password=${DB_PASSWORD:Silvestre1313.}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate 
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.id.new_generator_mappings=true

#  Logging 
logging.level.com.clinica.mscita=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# â”€ URLs de otros microservicios 
ms.paciente.url=${MS_PACIENTE_URL:http://localhost:8081}
ms.doctor.url=${MS_DOCTOR_URL:http://localhost:8082}


eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true
management.endpoints.web.exposure.include=health,info
springdoc.swagger-ui.path=/swagger-ui.html
